Models/Route.cs
namespace Avia_is.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Route")]
    public partial class Route
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDRoute { get; set; }

        [Required]
        [StringLength(50)]
        public string Departure_airport { get; set; }

        [Required]
        [StringLength(50)]
        public string Destination_airport { get; set; }

        
        public decimal Ticket_price { get; set; }

        public double Flight_duration { get; set; }

        public int IDFlight { get; set; }

        public virtual Flight Flight { get; set; }
    }
}

Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class PlanesController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Planes
        public ActionResult Index()
        {
            var plane = db.Plane.Include(p => p.Flight);
            return View(plane.ToList());
        }
        public ActionResult Inform()
        {
            var plane = db.Plane.Include(p => p.Flight);
            return View(plane.ToList());
        }

        // GET: Planes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }

        // GET: Planes/Create
        public ActionResult Create()
        {
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight");
            return View();
        }

        // POST: Planes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDBort,Model,Lifetime,Readiness,IDFlight")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                db.Plane.Add(plane);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // GET: Planes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // POST: Planes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDBort,Model,Lifetime,Readiness,IDFlight")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plane).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // GET: Planes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plane plane = db.Plane.Find(id);
            db.Plane.Remove(plane);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class RoutesController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Routes
        public ActionResult Index()
        {
            var route = db.Route.Include(r => r.Flight);
            return View(route.ToList());
        }
        public ActionResult Inform()
        {
            var route = db.Route.Include(r => r.Flight);
            return View(route.ToList());
        }

        // GET: Routes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight");
            return View();
        }

        // POST: Routes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDRoute,Departure_airport,Destination_airport,Ticket_price,Flight_duration,IDFlight")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Route.Add(route);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // GET: Routes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // POST: Routes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDRoute,Departure_airport,Destination_airport,Ticket_price,Flight_duration,IDFlight")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Entry(route).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // GET: Routes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Route route = db.Route.Find(id);
            db.Route.Remove(route);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Routes/Create.cshtml
@model Avia_is.Models.Route

@{
    ViewBag.Title = "Create";
}

<h2>Информация о маршруте</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Маршрут</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Номер рейса</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDRoute, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDRoute, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Аэропорт вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_airport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_airport, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
          <label class="control-label col-md-2">Аэропорт назначения</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination_airport, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination_airport, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Цена билета</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ticket_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ticket_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Продолжительность полета (мин.)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Flight_duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flight_duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Номер рейса</label>
            <div class="col-md-10">
                @Html.DropDownList("IDFlight", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDFlight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Routes/Delete.cshtml
@model Avia_is.Models.Route

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы уверены, что хотите выполнить это действие?</h3>
<div>
    <h4>Маршрут</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Номер рейса </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.IDFlight)
        </dd>

        <dt>
            <label>Аэропорт вылета </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_airport)
        </dd>

        <dt>
            <label>Аэропорт назначения </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination_airport)
        </dd>

        <dt>
            <label>Цена билета </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket_price)
        </dd>

        <dt>
            <label>Продолжительность полета (мин.) </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_duration)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться", "Index")
        </div>
    }
</div>

Views/Routes/Details.cshtml
@model Avia_is.Models.Route

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Маршрут</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Номер рейса </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.IDFlight)
        </dd>

        <dt>
            <label>Аэропорт вылета </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_airport)
        </dd>

        <dt>
            <label>Аэропорт назначения </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination_airport)
        </dd>

        <dt>
            <label>Цена билета </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket_price)
        </dd>

        <dt>
            <label>Продолжительность полета (мин.) </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_duration)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.IDRoute }) |
    @Html.ActionLink("Вернуться", "Index")
</p>

Views/Routes/Edit.cshtml
@model Avia_is.Models.Route

@{
    ViewBag.Title = "Edit";
}

<h2>Изменить</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Маршрут</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDRoute)

    <div class="form-group">
        <label class="control-label col-md-2">Аэропорт вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_airport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_airport, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Аэропорт назначения</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Destination_airport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Destination_airport, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <label class="control-label col-md-2">Цена билета</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ticket_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ticket_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Продолжительность полета (мин.)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Flight_duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flight_duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Номер рейса</label>
            <div class="col-md-10">
                @Html.DropDownList("IDFlight", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDFlight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Routes/Index.cshtml
@model IEnumerable<Avia_is.Models.Route>

@{
    ViewBag.Title = "Маршрут";
}

<h2>Информация о маршруте</h2>

<p>
    @Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Далее", "Index", "Planes", null, new { @class = "btn btn-warning" })
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID рейса</th>
            <th>Аэропорт вылета </th>
            <th>Аэропорт назначения </th>
            <th>Цена билета(руб.)</th>
            <th>Продолжительность полета(мин.)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight.IDFlight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_airport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destination_airport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ticket_price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight_duration)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", new { id = item.IDRoute }) |
                    @Html.ActionLink("Детали", "Details", new { id = item.IDRoute }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.IDRoute })
                </td>
            </tr>
        }
       </tbody>
</table>

Views/Routes/Inform.cshtml
@model IEnumerable<Avia_is.Models.Route>

@{
    ViewBag.Title = "Маршрут";
}

<h2>Информация о маршруте</h2>
<p>
    @Html.ActionLink("Вернуться на главную", "Index", "Home", null, new { @class = "btn btn-warning" })

</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID рейса</th>
            <th>Аэропорт вылета </th>
            <th>Аэропорт назначения </th>
            <th>Цена билета(руб.)</th>
            <th>Продолжительность полета(мин.)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight.IDFlight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_airport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destination_airport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ticket_price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight_duration)
                </td>

            </tr>
        }
    </tbody>
</table>