Models/Plane.cs
namespace Avia_is.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Plane")]
    public partial class Plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plane()
        {
            Commander = new HashSet<Commander>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDBort { get; set; }

        [Required]
        [StringLength(10)]
        public string Model { get; set; }

        public byte Lifetime { get; set; }

        public bool Readiness { get; set; }

        public int IDFlight { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commander> Commander { get; set; }

        public virtual Flight Flight { get; set; }
    }
}

Controllers/CommandersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class CommandersController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Commanders
        public ActionResult Index()
        {
            var commander = db.Commander.Include(c => c.Plane);
            return View(commander.ToList());
        }
        public ActionResult Inform()
        {
            var commander = db.Commander.Include(c => c.Plane);
            return View(commander.ToList());
        }

        // GET: Commanders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commander commander = db.Commander.Find(id);
            if (commander == null)
            {
                return HttpNotFound();
            }
            return View(commander);
        }

        // GET: Commanders/Create
        public ActionResult Create()
        {
            ViewBag.IDBort = new SelectList(db.Plane, "IDBort", "Model");
            return View();
        }

        // POST: Commanders/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_number,Lastname,Name,Patronymic,Address,Flying_hours,IDBort")] Commander commander)
        {
            if (ModelState.IsValid)
            {
                db.Commander.Add(commander);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDBort = new SelectList(db.Plane, "IDBort", "Model", commander.IDBort);
            return View(commander);
        }

        // GET: Commanders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commander commander = db.Commander.Find(id);
            if (commander == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDBort = new SelectList(db.Plane, "IDBort", "Model", commander.IDBort);
            return View(commander);
        }

        // POST: Commanders/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_number,Lastname,Name,Patronymic,Address,Flying_hours,IDBort")] Commander commander)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commander).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDBort = new SelectList(db.Plane, "IDBort", "Model", commander.IDBort);
            return View(commander);
        }

        // GET: Commanders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commander commander = db.Commander.Find(id);
            if (commander == null)
            {
                return HttpNotFound();
            }
            return View(commander);
        }

        // POST: Commanders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Commander commander = db.Commander.Find(id);
            db.Commander.Remove(commander);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class PlanesController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Planes
        public ActionResult Index()
        {
            var plane = db.Plane.Include(p => p.Flight);
            return View(plane.ToList());
        }
        public ActionResult Inform()
        {
            var plane = db.Plane.Include(p => p.Flight);
            return View(plane.ToList());
        }

        // GET: Planes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }

        // GET: Planes/Create
        public ActionResult Create()
        {
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight");
            return View();
        }

        // POST: Planes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDBort,Model,Lifetime,Readiness,IDFlight")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                db.Plane.Add(plane);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // GET: Planes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // POST: Planes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDBort,Model,Lifetime,Readiness,IDFlight")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plane).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", plane.IDFlight);
            return View(plane);
        }

        // GET: Planes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Plane.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plane plane = db.Plane.Find(id);
            db.Plane.Remove(plane);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Planes/Create.cshtml
@model Avia_is.Models.Plane

@{
    ViewBag.Title = "Create";
}

<h2>Информация о самолете</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Самолет</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Бортовой номер</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDBort, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDBort, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Модель</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Срок эксплуатации(лет)</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lifetime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lifetime, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <label class="control-label col-md-2">Готовность</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Readiness)
                    @Html.ValidationMessageFor(model => model.Readiness, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Номер рейса</label>
            <div class="col-md-10">
                @Html.DropDownList("IDFlight", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDFlight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
                
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Planes/Delete.cshtml
@model Avia_is.Models.Plane

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы уверены, что хотите выполнить это действие?</h3>
<div>
    <h4>Самолет</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Номер рейса</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.IDFlight)
        </dd>

        <dt>
            <label>Модель</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            <label>Срок эксплуатации(лет)</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lifetime)
        </dd>

        <dt>
            <label>Готовность</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Readiness)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться", "Index")
        </div>
    }
</div>

Views/Planes/Details.cshtml
@model Avia_is.Models.Plane

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Самолет</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Номер рейса</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.IDFlight)
        </dd>

        <dt>
            <label>Модель</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            <label>Срок эксплуатации(лет)</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lifetime)
        </dd>

        <dt>
            <label>Готовность</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Readiness)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.IDBort }) |
    @Html.ActionLink("Вернуться", "Index")
</p>

Views/Planes/Edit.cshtml
@model Avia_is.Models.Plane

@{
    ViewBag.Title = "Edit";
}

<h2>Изменить</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Самолет</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDBort)

    <div class="form-group">
        <label class="control-label col-md-2">Модель</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Срок эксплуатации(лет)</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lifetime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lifetime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Готовность</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Readiness)
                @Html.ValidationMessageFor(model => model.Readiness, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Номер рейса</label>
        <div class="col-md-10">
            @Html.DropDownList("IDFlight", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDFlight, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Planes/Index.cshtml
@model IEnumerable<Avia_is.Models.Plane>

@{
    ViewBag.Title = "Самолет";
}

<h2>Информация о самолете</h2>

<p>
    @Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Далее", "Index", "Commanders", null, new { @class = "btn btn-warning" })
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID маршрута</th>
            <th>Модель </th>
            <th>Срок эксплуатации(лет) </th>
            <th>Готовность</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight.IDFlight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lifetime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Readiness)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", new { id = item.IDBort }) |
                    @Html.ActionLink("Детали", "Details", new { id = item.IDBort }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.IDBort })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Planes/Inform.cshtml
@model IEnumerable<Avia_is.Models.Plane>

@{
    ViewBag.Title = "Inform";
}

<h2>Информация о самолетах</h2>

<p>
    @Html.ActionLink("Вернуться на главную", "Index", "Home", null, new { @class = "btn btn-warning" })

</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID маршрута</th>
            <th>Модель </th>
            <th>Срок эксплуатации(лет) </th>
            <th>Готовность</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Flight.IDFlight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lifetime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Readiness)
            </td>

        </tr>
        }
    </tbody>
</table>