Controllers/AviaPassengersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class AviaPassengersController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: AviaPassengers
        public ActionResult Index()
        {
            return View(db.AviaPassenger.ToList());
        }
        public ActionResult Inform()
        {
            return View(db.AviaPassenger.ToList());
        }
        // GET: AviaPassengers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AviaPassenger aviaPassenger = db.AviaPassenger.Find(id);
            if (aviaPassenger == null)
            {
                return HttpNotFound();
            }
            return View(aviaPassenger);
        }

        // GET: AviaPassengers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AviaPassengers/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDPassport,Lastname,Name,Patronymic,Address,Telephone")] AviaPassenger aviaPassenger)
        {
            if (ModelState.IsValid)
            {
                db.AviaPassenger.Add(aviaPassenger);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aviaPassenger);
        }

        // GET: AviaPassengers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AviaPassenger aviaPassenger = db.AviaPassenger.Find(id);
            if (aviaPassenger == null)
            {
                return HttpNotFound();
            }
            return View(aviaPassenger);
        }

        // POST: AviaPassengers/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDPassport,Lastname,Name,Patronymic,Address,Telephone")] AviaPassenger aviaPassenger)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aviaPassenger).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aviaPassenger);
        }

        // GET: AviaPassengers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AviaPassenger aviaPassenger = db.AviaPassenger.Find(id);
            if (aviaPassenger == null)
            {
                return HttpNotFound();
            }
            return View(aviaPassenger);
        }

        // POST: AviaPassengers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AviaPassenger aviaPassenger = db.AviaPassenger.Find(id);
            db.AviaPassenger.Remove(aviaPassenger);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class HomeController : Controller
    {
        private avia_databaseContext db;

        public HomeController()
        {
            db = new avia_databaseContext();
        }
        public ActionResult Index()
        {
            var data = db.Flight.Include(p => p.Plane).ToList();

            return View(data);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

            public ActionResult GetMessage()
            {
            string[] states = new string[] { "Номер маршрута", "Номер рейса", "Аэропорт вылета", "Аэропорт назначения", "Время полета", "Бортовой номер", "Готовность самолета к вылету", "Готовность рейса", "ID командира", "Доход" };
                return PartialView(states);
            }
           
        
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/GetMessage.cshtml
@model IEnumerable<string>

    <h2>Основная информация</h2>
<table class="table table-striped" >
    <thead>
        <tr>
            @foreach (string t in Model)
            {

                <th>@t</th>
            }
        </tr>
    </thead>
    <tbody>
        <tr>
            @foreach (string t in Model)
            {

                <td>@t</td>
            }
        </tr>
    </tbody>
</table>

Views/Home/Index.cshtml
@model IEnumerable<Avia_is.Models.Flight>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron jumbotron-fluid">
    <h2 align="center" color="black">Информационная система авиакомпании "Полёт"</h2>
    <p class="lead"></p>
    <p>@Html.ActionLink("Создать новое", "Index", "AviaPassengers", null, new { @class = "btn btn-primary" })</p>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Номер маршрута </th>
            <th>Аэропорт вылета </th>
            <th>Аэропорт назначения </th>
            <th>Стоимость билета(руб.) </th>
            <th>Время полета(мин.) </th>
            <th>Модель самолета </th>
            <th>Готовность самолета </th>
            <th>Номер самолета </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => item.IDFlight)
                </td>

                @foreach (var r in item.Route)
                {

                    <td>
                        @Html.DisplayFor(modelitem => r.Departure_airport)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => r.Destination_airport)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => r.Ticket_price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => r.Flight_duration)
                    </td>

                    foreach (var d in item.Plane)
                    {


                        <td>
                            @Html.DisplayFor(modelitem => d.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => d.Readiness)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => d.IDBort)
                        </td>

                    }
                }
            </tr>
        }
    </tbody>
</table>