Models/Flight.cs
namespace Avia_is.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Flight")]
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            Plane = new HashSet<Plane>();
            Route = new HashSet<Route>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDFlight { get; set; }

        [Column(TypeName = "date")]
        public DateTime Departure_date { get; set; }

        public TimeSpan Departure_time { get; set; }

        public bool Readiness { get; set; }

        public int IDPassport { get; set; }

        public virtual AviaPassenger AviaPassenger { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plane> Plane { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Route { get; set; }
    }
}

Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class FlightsController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Flights
        public ActionResult Index()
        {
            var flight = db.Flight.Include(f => f.AviaPassenger);
            return View(flight.ToList());
        }
        public ActionResult Inform()
        {
            var flight = db.Flight.Include(f => f.AviaPassenger);
            return View(flight.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        public ActionResult Create()
        {
            ViewBag.IDPassport = new SelectList(db.AviaPassenger, "IDPassport", "Lastname");
            return View();
        }

        // POST: Flights/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDFlight,Departure_date,Departure_time,Readiness,IDPassport")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Flight.Add(flight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDPassport = new SelectList(db.AviaPassenger, "IDPassport", "Lastname", flight.IDPassport);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPassport = new SelectList(db.AviaPassenger, "IDPassport", "Lastname", flight.IDPassport);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDFlight,Departure_date,Departure_time,Readiness,IDPassport")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDPassport = new SelectList(db.AviaPassenger, "IDPassport", "Lastname", flight.IDPassport);
            return View(flight);
        }

        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flight.Find(id);
            db.Flight.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avia_is.Models;

namespace Avia_is.Controllers
{
    public class RoutesController : Controller
    {
        private avia_databaseContext db = new avia_databaseContext();

        // GET: Routes
        public ActionResult Index()
        {
            var route = db.Route.Include(r => r.Flight);
            return View(route.ToList());
        }
        public ActionResult Inform()
        {
            var route = db.Route.Include(r => r.Flight);
            return View(route.ToList());
        }

        // GET: Routes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight");
            return View();
        }

        // POST: Routes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDRoute,Departure_airport,Destination_airport,Ticket_price,Flight_duration,IDFlight")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Route.Add(route);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // GET: Routes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // POST: Routes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDRoute,Departure_airport,Destination_airport,Ticket_price,Flight_duration,IDFlight")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Entry(route).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDFlight = new SelectList(db.Flight, "IDFlight", "IDFlight", route.IDFlight);
            return View(route);
        }

        // GET: Routes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Route.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Route route = db.Route.Find(id);
            db.Route.Remove(route);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Flights/Create.cshtml
@model Avia_is.Models.Flight

@{
    ViewBag.Title = "Create";
}

<h2>Информация о рейсе</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Рейс</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Номер рейса</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDFlight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDFlight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Дата вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Время вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Готовность</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Readiness)
                @Html.ValidationMessageFor(model => model.Readiness, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Номер паспорта</label>
        <div class="col-md-10">
            @Html.DropDownList("IDPassport", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDPassport, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
              
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Flights/Delete.cshtml
@model Avia_is.Models.Flight

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы уверены, что хотите выполнить это действие?</h3>
<div>
    <h4>Рейс</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Фамилия</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AviaPassenger.Lastname)
        </dd>

        <dt>
            <label>Дата вылета</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_date)
        </dd>

        <dt>
            <label>Время вылета</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_time)
        </dd>

        <dt>
            <label>Готовность</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Readiness)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться", "Index")
        </div>
    }
</div>

Views/Flights/Details.cshtml
@model Avia_is.Models.Flight

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Рейс</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Фамилия</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AviaPassenger.Lastname)
        </dd>

        <dt>
            <label>Дата вылета</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_date)
        </dd>

        <dt>
            <label>Время вылета</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departure_time)
        </dd>

        <dt>
            <label>Готовность</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Readiness)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.IDFlight }) |
    @Html.ActionLink("Вернуться", "Index")
</p>

Views/Flights/Edit.cshtml
@model Avia_is.Models.Flight

@{
    ViewBag.Title = "Edit";
}

<h2>Изменить</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Рейс</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDFlight)

    <div class="form-group">
        <label class="control-label col-md-2">Дата вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Время вылета</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departure_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departure_time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Готовность</label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Readiness)
                @Html.ValidationMessageFor(model => model.Readiness, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Номер паспорта</label>
        <div class="col-md-10">
            @Html.DropDownList("IDPassport", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDPassport, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Flights/Index.cshtml
@model IEnumerable<Avia_is.Models.Flight>

@{
    ViewBag.Title = "Рейс";
}

<h2>Информация о рейсе</h2>

<p>
    @Html.ActionLink("Создать", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Далее", "Index", "Routes", null, new { @class = "btn btn-warning" })

</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Фамилия пассажира</th>
            <th>Дата вылета </th>
            <th>Время вылета </th>
            <th>Готовность</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AviaPassenger.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Readiness)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", new { id = item.IDFlight }) |
                    @Html.ActionLink("Детали", "Details", new { id = item.IDFlight }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.IDFlight })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Flights/Inform.cshtml
@model IEnumerable<Avia_is.Models.Flight>

@{
    ViewBag.Title = "Inform";
}

<h2>Информация о рейсах</h2>

<p>
    @Html.ActionLink("Вернуться на главную", "Index", "Home", null, new { @class = "btn btn-warning" })

</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Фамилия пассажира</th>
            <th>Дата вылета </th>
            <th>Время вылета </th>
            <th>Готовность</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AviaPassenger.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure_time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Readiness)
                </td>

            </tr>
        }
    </tbody>
</table>